// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sem9.Models;

#nullable disable

namespace sem9.Migrations
{
    [DbContext(typeof(TesisContext))]
    partial class TesisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sem9.Models.Asesor", b =>
                {
                    b.Property<int>("IdAsesor")
                        .HasColumnType("int")
                        .HasColumnName("idAsesor");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Carrera")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("carrera");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdAsesor")
                        .HasName("PK__ASESOR__A801FCE9550BEADD");

                    b.ToTable("ASESOR", (string)null);
                });

            modelBuilder.Entity("sem9.Models.AsignarAsesor", b =>
                {
                    b.Property<int>("IdAsignar")
                        .HasColumnType("int")
                        .HasColumnName("idAsignar");

                    b.Property<int>("IdAsesor")
                        .HasColumnType("int")
                        .HasColumnName("idAsesor");

                    b.Property<int>("IdTesis")
                        .HasColumnType("int")
                        .HasColumnName("idTesis");

                    b.HasKey("IdAsignar")
                        .HasName("PK__ASIGNAR___8319E6556D1245BF");

                    b.HasIndex("IdAsesor");

                    b.HasIndex("IdTesis");

                    b.ToTable("ASIGNAR_ASESOR", (string)null);
                });

            modelBuilder.Entity("sem9.Models.AsignarEstudiante", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .HasColumnType("int")
                        .HasColumnName("idAsignacion");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("idEstudiante");

                    b.Property<int>("IdTesis")
                        .HasColumnType("int")
                        .HasColumnName("idTesis");

                    b.HasKey("IdAsignacion")
                        .HasName("PK__ASIGNAR___E17144781DF73DD8");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdTesis");

                    b.ToTable("ASIGNAR_ESTUDIANTE", (string)null);
                });

            modelBuilder.Entity("sem9.Models.AsignarJurado", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .HasColumnType("int")
                        .HasColumnName("idAsignacion");

                    b.Property<int>("IdJurado")
                        .HasColumnType("int")
                        .HasColumnName("idJurado");

                    b.Property<int>("IdSustentacion")
                        .HasColumnType("int")
                        .HasColumnName("idSustentacion");

                    b.HasKey("IdAsignacion")
                        .HasName("PK__ASIGNAR___E1714478BA6D2F3A");

                    b.HasIndex("IdJurado");

                    b.HasIndex("IdSustentacion");

                    b.ToTable("ASIGNAR_JURADO", (string)null);
                });

            modelBuilder.Entity("sem9.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("idEstudiante");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Carrera")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("carrera");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdEstudiante")
                        .HasName("PK__ESTUDIAN__AEFFDBC50AAD64AA");

                    b.ToTable("ESTUDIANTE", (string)null);
                });

            modelBuilder.Entity("sem9.Models.Jurado", b =>
                {
                    b.Property<int>("IdJurado")
                        .HasColumnType("int")
                        .HasColumnName("idJurado");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Carrera")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("carrera");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdJurado")
                        .HasName("PK__JURADO__778A32DEAF695123");

                    b.ToTable("JURADO", (string)null);
                });

            modelBuilder.Entity("sem9.Models.PagoCarpeta", b =>
                {
                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("idPago");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("idEstudiante");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("metodoPago");

                    b.HasKey("IdPago")
                        .HasName("PK__PAGO_CAR__BD2295AD2DB412E0");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("PAGO_CARPETA", (string)null);
                });

            modelBuilder.Entity("sem9.Models.SolicitudTesis", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("idSolicitud");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("idPago");

                    b.HasKey("IdSolicitud")
                        .HasName("PK__SOLICITU__D801DDB8210A1D2F");

                    b.HasIndex("IdPago");

                    b.ToTable("SOLICITUD_TESIS", (string)null);
                });

            modelBuilder.Entity("sem9.Models.SustentacionFinal", b =>
                {
                    b.Property<int>("IdSustentacion")
                        .HasColumnType("int")
                        .HasColumnName("idSustentacion");

                    b.Property<string>("Calificacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("calificacion");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdTesis")
                        .HasColumnType("int")
                        .HasColumnName("idTesis");

                    b.Property<string>("Modalidad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("modalidad");

                    b.HasKey("IdSustentacion")
                        .HasName("PK__SUSTENTA__F5B1C0083188C7C2");

                    b.HasIndex("IdTesis");

                    b.ToTable("SUSTENTACION_FINAL", (string)null);
                });

            modelBuilder.Entity("sem9.Models.Tesis", b =>
                {
                    b.Property<int>("IdTesis")
                        .HasColumnType("int")
                        .HasColumnName("idTesis");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fechaInicio");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int")
                        .HasColumnName("idEstudiante");

                    b.Property<string>("LineaInvestigacion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lineaInvestigacion");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text")
                        .HasColumnName("objetivo");

                    b.Property<string>("TipoTesis")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipoTesis");

                    b.HasKey("IdTesis")
                        .HasName("PK__TESIS__2E2073ED92DF67BA");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("TESIS", (string)null);
                });

            modelBuilder.Entity("sem9.Models.AsignarAsesor", b =>
                {
                    b.HasOne("sem9.Models.Asesor", "IdAsesorNavigation")
                        .WithMany("AsignarAsesors")
                        .HasForeignKey("IdAsesor")
                        .IsRequired()
                        .HasConstraintName("FK__ASIGNAR_A__idAse__44FF419A");

                    b.HasOne("sem9.Models.Tesis", "IdTesisNavigation")
                        .WithMany("AsignarAsesors")
                        .HasForeignKey("IdTesis")
                        .IsRequired()
                        .HasConstraintName("FK__ASIGNAR_A__idTes__440B1D61");

                    b.Navigation("IdAsesorNavigation");

                    b.Navigation("IdTesisNavigation");
                });

            modelBuilder.Entity("sem9.Models.AsignarEstudiante", b =>
                {
                    b.HasOne("sem9.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("AsignarEstudiantes")
                        .HasForeignKey("IdEstudiante")
                        .IsRequired()
                        .HasConstraintName("FK__ASIGNAR_E__idEst__412EB0B6");

                    b.HasOne("sem9.Models.Tesis", "IdTesisNavigation")
                        .WithMany("AsignarEstudiantes")
                        .HasForeignKey("IdTesis")
                        .IsRequired()
                        .HasConstraintName("FK__ASIGNAR_E__idTes__403A8C7D");

                    b.Navigation("IdEstudianteNavigation");

                    b.Navigation("IdTesisNavigation");
                });

            modelBuilder.Entity("sem9.Models.AsignarJurado", b =>
                {
                    b.HasOne("sem9.Models.Jurado", "IdJuradoNavigation")
                        .WithMany("AsignarJurados")
                        .HasForeignKey("IdJurado")
                        .IsRequired()
                        .HasConstraintName("FK__ASIGNAR_J__idJur__5165187F");

                    b.HasOne("sem9.Models.SustentacionFinal", "IdSustentacionNavigation")
                        .WithMany("AsignarJurados")
                        .HasForeignKey("IdSustentacion")
                        .IsRequired()
                        .HasConstraintName("FK__ASIGNAR_J__idSus__5070F446");

                    b.Navigation("IdJuradoNavigation");

                    b.Navigation("IdSustentacionNavigation");
                });

            modelBuilder.Entity("sem9.Models.PagoCarpeta", b =>
                {
                    b.HasOne("sem9.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("PagoCarpeta")
                        .HasForeignKey("IdEstudiante")
                        .IsRequired()
                        .HasConstraintName("FK__PAGO_CARP__idEst__47DBAE45");

                    b.Navigation("IdEstudianteNavigation");
                });

            modelBuilder.Entity("sem9.Models.SolicitudTesis", b =>
                {
                    b.HasOne("sem9.Models.PagoCarpeta", "IdPagoNavigation")
                        .WithMany("SolicitudTesis")
                        .HasForeignKey("IdPago")
                        .IsRequired()
                        .HasConstraintName("FK__SOLICITUD__idPag__4AB81AF0");

                    b.Navigation("IdPagoNavigation");
                });

            modelBuilder.Entity("sem9.Models.SustentacionFinal", b =>
                {
                    b.HasOne("sem9.Models.Tesis", "IdTesisNavigation")
                        .WithMany("SustentacionFinals")
                        .HasForeignKey("IdTesis")
                        .IsRequired()
                        .HasConstraintName("FK__SUSTENTAC__idTes__4D94879B");

                    b.Navigation("IdTesisNavigation");
                });

            modelBuilder.Entity("sem9.Models.Tesis", b =>
                {
                    b.HasOne("sem9.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("Tesis")
                        .HasForeignKey("IdEstudiante")
                        .IsRequired()
                        .HasConstraintName("FK__TESIS__idEstudia__3D5E1FD2");

                    b.Navigation("IdEstudianteNavigation");
                });

            modelBuilder.Entity("sem9.Models.Asesor", b =>
                {
                    b.Navigation("AsignarAsesors");
                });

            modelBuilder.Entity("sem9.Models.Estudiante", b =>
                {
                    b.Navigation("AsignarEstudiantes");

                    b.Navigation("PagoCarpeta");

                    b.Navigation("Tesis");
                });

            modelBuilder.Entity("sem9.Models.Jurado", b =>
                {
                    b.Navigation("AsignarJurados");
                });

            modelBuilder.Entity("sem9.Models.PagoCarpeta", b =>
                {
                    b.Navigation("SolicitudTesis");
                });

            modelBuilder.Entity("sem9.Models.SustentacionFinal", b =>
                {
                    b.Navigation("AsignarJurados");
                });

            modelBuilder.Entity("sem9.Models.Tesis", b =>
                {
                    b.Navigation("AsignarAsesors");

                    b.Navigation("AsignarEstudiantes");

                    b.Navigation("SustentacionFinals");
                });
#pragma warning restore 612, 618
        }
    }
}
